#  Attention!
#  Available only for demonstration, real parameters must be private!
#-----------
spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: authentication_server
      authentication-database: admin
      auto-index-creation: true


#  Attention!
#  Available only for demonstration, real parameters must be private!
#------------
jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==